export type Producto = {
  id: number
  nombre: string
  precio: number
  stock: number
  descripcion: string
  imagen: string
}

export type Vendedor = {
  id: number
  nombre: string
  descripcion: string
  imagen: string
  ubicacion: string
  productos: Producto[]
}

export const vendedores: Vendedor[] = [
  {
    id: 1,
    nombre: "Verde Natural",
    descripcion: "Especialistas en plantas de interior y suculentas",
    imagen: "",
    ubicacion: "Buenos Aires",
    productos: [
      { id: 1, nombre: "Monstera Deliciosa", precio: 28000, stock: 6, descripcion: "Planta tropical de interior, hojas grandes y decorativas", imagen: "" },
      { id: 2, nombre: "Pilea Peperomioides", precio: 16000, stock: 10, descripcion: "Planta redonda y llamativa, perfecta para escritorios", imagen: "" },
      { id: 3, nombre: "Sansevieria Laurentii", precio: 22000, stock: 8, descripcion: "Planta resistente, ideal para principiantes", imagen: "" },
      { id: 4, nombre: "Pothos Dorado", precio: 10000, stock: 20, descripcion: "Colgante de rápido crecimiento y muy resistente", imagen: "" },
      { id: 5, nombre: "Spathiphyllum", precio: 15000, stock: 12, descripcion: "Purificador de aire con flores blancas elegantes", imagen: "" },
      { id: 6, nombre: "Aglaonema Rojo", precio: 25000, stock: 7, descripcion: "Planta de follaje colorido para interior", imagen: "" },
      { id: 7, nombre: "Ficus Elastica", precio: 32000, stock: 5, descripcion: "Árbol de interior de hojas grandes y brillantes", imagen: "" },
      { id: 8, nombre: "Tradescantia Zebrina", precio: 7000, stock: 25, descripcion: "Colgante con hojas moradas y plateadas", imagen: "" },
      { id: 9, nombre: "Haworthia", precio: 6000, stock: 18, descripcion: "Suculenta de interior ideal para poca luz", imagen: "" },
      { id: 10, nombre: "Zamioculca", precio: 20000, stock: 9, descripcion: "Resistente y elegante, perfecta para oficinas", imagen: "" },
      { id: 11, nombre: "Dracaena Marginata", precio: 18000, stock: 11, descripcion: "Planta arbustiva de hojas largas y finas", imagen: "" },
      { id: 12, nombre: "Calathea Orbifolia", precio: 30000, stock: 4, descripcion: "Hojas plateadas con rayas verdes únicas", imagen: "" },
    ]
  },
  {
    id: 2,
    nombre: "El Vivero del Sur",
    descripcion: "Plantas de exterior, aromáticas y frutales",
    imagen: "",
    ubicacion: "Córdoba",
    productos: [
      { id: 13, nombre: "Lavanda", precio: 8000, stock: 15, descripcion: "Aromática ideal para jardines y balcones", imagen: "" },
      { id: 14, nombre: "Romero", precio: 6000, stock: 20, descripcion: "Hierba aromática y culinaria muy resistente", imagen: "" },
      { id: 15, nombre: "Limonero", precio: 45000, stock: 3, descripcion: "Frutal en maceta, da frutos todo el año", imagen: "" },
      { id: 16, nombre: "Naranjo Enano", precio: 40000, stock: 4, descripcion: "Cítrico compacto ideal para balcones", imagen: "" },
      { id: 17, nombre: "Tomillo", precio: 4500, stock: 25, descripcion: "Aromática culinaria muy resistente", imagen: "" },
      { id: 18, nombre: "Salvia", precio: 5000, stock: 18, descripcion: "Aromática con propiedades medicinales", imagen: "" },
      { id: 19, nombre: "Geranio Rojo", precio: 7000, stock: 20, descripcion: "Flor de balcón resistente y colorida", imagen: "" },
      { id: 20, nombre: "Begonia", precio: 8000, stock: 15, descripcion: "Flor de jardín ideal para lugares húmedos", imagen: "" },
      { id: 21, nombre: "Menta", precio: 4000, stock: 30, descripcion: "Aromática ideal para infusiones y cocina", imagen: "" },
      { id: 22, nombre: "Albahaca", precio: 3500, stock: 35, descripcion: "Hierba culinaria esencial", imagen: "" },
      { id: 23, nombre: "Perejil", precio: 3000, stock: 30, descripcion: "Hierba culinaria fresca y resistente", imagen: "" },
      { id: 24, nombre: "Higuera Enana", precio: 35000, stock: 3, descripcion: "Frutal en maceta que da higos dulces", imagen: "" },
      { id: 25, nombre: "Jazmín Trepador", precio: 12000, stock: 8, descripcion: "Flor perfumada ideal para enrejar", imagen: "" },
      { id: 26, nombre: "Lavanda Francesa", precio: 9000, stock: 12, descripcion: "Variedad aromática muy resistente", imagen: "" },
      { id: 27, nombre: "Coriandro", precio: 3000, stock: 25, descripcion: "Hierba culinaria de sabor intenso", imagen: "" },
    ]
  },
  {
    id: 3,
    nombre: "Cactus & Co",
    descripcion: "Cactus, suculentas y plantas de bajo mantenimiento",
    imagen: "",
    ubicacion: "Rosario",
    productos: [
      { id: 28, nombre: "Cactus San Pedro", precio: 12000, stock: 5, descripcion: "Cactus columnar de rápido crecimiento", imagen: "" },
      { id: 29, nombre: "Echeveria Rosa", precio: 5000, stock: 25, descripcion: "Suculenta rosada perfecta para combinar", imagen: "" },
      { id: 30, nombre: "Aloe Vera", precio: 9000, stock: 12, descripcion: "Planta medicinal y decorativa muy resistente", imagen: "" },
      { id: 31, nombre: "Sedum Burro", precio: 6000, stock: 18, descripcion: "Suculenta colgante de hojas gordas", imagen: "" },
      { id: 32, nombre: "Gymnocalycium", precio: 8000, stock: 15, descripcion: "Cactus globoso de flores llamativas", imagen: "" },
      { id: 33, nombre: "Agave Azul", precio: 15000, stock: 8, descripcion: "Suculenta grande ideal para exteriores", imagen: "" },
      { id: 34, nombre: "Crassula Ovata", precio: 7000, stock: 20, descripcion: "Planta de jade símbolo de buena suerte", imagen: "" },
      { id: 35, nombre: "Lithops", precio: 9000, stock: 10, descripcion: "Las piedras vivas más curiosas del mundo vegetal", imagen: "" },
      { id: 36, nombre: "Mammillaria", precio: 6000, stock: 22, descripcion: "Cactus globoso con corona de flores", imagen: "" },
      { id: 37, nombre: "Opuntia", precio: 10000, stock: 10, descripcion: "Cactus paleta clásico y resistente", imagen: "" },
      { id: 38, nombre: "Kalanchoe", precio: 8000, stock: 16, descripcion: "Suculenta de flor larga duración", imagen: "" },
    ]
  },
  {
    id: 4,
    nombre: "Jardín Secreto",
    descripcion: "Plantas raras, importadas y de colección",
    imagen: "",
    ubicacion: "Mendoza",
    productos: [
      { id: 39, nombre: "Monstera Thai Constellation", precio: 120000, stock: 2, descripcion: "Variedad premium con manchas blancas únicas", imagen: "" },
      { id: 40, nombre: "Philodendron Pink Princess", precio: 85000, stock: 1, descripcion: "Rarísima planta con hojas rosadas y verdes", imagen: "" },
      { id: 41, nombre: "Alocasia Zebrina", precio: 35000, stock: 4, descripcion: "Tallos rayados como cebra, muy llamativa", imagen: "" },
      { id: 42, nombre: "Hoya Kerrii", precio: 18000, stock: 8, descripcion: "La planta corazón, ideal para regalar", imagen: "" },
      { id: 43, nombre: "Anthurium Clarinervium", precio: 65000, stock: 2, descripcion: "Hojas aterciopeladas con venas blancas", imagen: "" },
      { id: 44, nombre: "Philodendron Gloriosum", precio: 75000, stock: 2, descripcion: "Hojas gigantes con venas blancas llamativas", imagen: "" },
      { id: 45, nombre: "Begonia Maculata", precio: 28000, stock: 5, descripcion: "Hojas con lunares blancos únicos", imagen: "" },
      { id: 46, nombre: "Calathea White Fusion", precio: 45000, stock: 3, descripcion: "La calathea más rara y buscada", imagen: "" },
      { id: 47, nombre: "Monstera Adansonii", precio: 22000, stock: 6, descripcion: "Monstera perforada de crecimiento trepador", imagen: "" },
      { id: 48, nombre: "Alocasia Black Velvet", precio: 55000, stock: 2, descripcion: "Hojas negras aterciopeladas únicas", imagen: "" },
    ]
  },
  {
    id: 5,
    nombre: "La Huerta Urbana",
    descripcion: "Plantas comestibles, huertas y kits de cultivo",
    imagen: "",
    ubicacion: "Buenos Aires",
    productos: [
      { id: 49, nombre: "Kit Huerta Inicial", precio: 18000, stock: 8, descripcion: "Todo lo que necesitás para empezar tu huerta", imagen: "" },
      { id: 50, nombre: "Tomate Cherry", precio: 7000, stock: 15, descripcion: "Planta de tomate lista para trasplantar", imagen: "" },
      { id: 51, nombre: "Albahaca", precio: 4000, stock: 30, descripcion: "Hierba aromática ideal para cocina", imagen: "" },
      { id: 52, nombre: "Lechuga Mantecosa", precio: 2500, stock: 40, descripcion: "Lechuga lista para trasplantar", imagen: "" },
      { id: 53, nombre: "Espinaca", precio: 2500, stock: 35, descripcion: "Verdura de hoja nutritiva y rápida", imagen: "" },
      { id: 54, nombre: "Zapallito", precio: 3000, stock: 20, descripcion: "Planta de zapallito ideal para huerta", imagen: "" },
      { id: 55, nombre: "Pimiento", precio: 4000, stock: 18, descripcion: "Planta de pimiento de varios colores", imagen: "" },
      { id: 56, nombre: "Berenjena", precio: 4000, stock: 15, descripcion: "Verdura de verano ideal para huerta", imagen: "" },
      { id: 57, nombre: "Frutilla", precio: 5000, stock: 25, descripcion: "Planta de frutilla ideal para maceta", imagen: "" },
      { id: 58, nombre: "Perejil Rizado", precio: 3000, stock: 30, descripcion: "Hierba culinaria fresca y decorativa", imagen: "" },
      { id: 59, nombre: "Cebolla de Verdeo", precio: 2000, stock: 40, descripcion: "Lista para cosechar en pocas semanas", imagen: "" },
      { id: 60, nombre: "Rabanito", precio: 2000, stock: 35, descripcion: "Cultivo rápido ideal para principiantes", imagen: "" },
      { id: 61, nombre: "Tierra Orgánica Premium", precio: 8000, stock: 20, descripcion: "Sustrato enriquecido para huerta", imagen: "" },
      { id: 62, nombre: "Fertilizante Orgánico", precio: 6000, stock: 25, descripcion: "Abono natural para mejores cosechas", imagen: "" },
    ]
  },
  {
    id: 6,
    nombre: "Tropicales del Norte",
    descripcion: "Palmeras, helechos y plantas tropicales",
    imagen: "",
    ubicacion: "Salta",
    productos: [
      { id: 63, nombre: "Palmera Areca", precio: 55000, stock: 4, descripcion: "Palmera elegante para interiores luminosos", imagen: "" },
      { id: 64, nombre: "Helecho Boston", precio: 12000, stock: 9, descripcion: "Helecho frondoso ideal para ambientes húmedos", imagen: "" },
      { id: 65, nombre: "Bromelia", precio: 20000, stock: 6, descripcion: "Planta colorida de origen tropical", imagen: "" },
      { id: 66, nombre: "Heliconia", precio: 40000, stock: 4, descripcion: "Flor tropical exótica de gran impacto visual", imagen: "" },
      { id: 67, nombre: "Anthurium", precio: 25000, stock: 7, descripcion: "Planta de flor roja lacada muy llamativa", imagen: "" },
      { id: 68, nombre: "Costus", precio: 18000, stock: 6, descripcion: "Planta tropical de follaje decorativo", imagen: "" },
      { id: 69, nombre: "Palmera Kentia", precio: 75000, stock: 2, descripcion: "La palmera de interior más elegante", imagen: "" },
      { id: 70, nombre: "Strelitzia", precio: 35000, stock: 5, descripcion: "Ave del paraíso, flor tropical icónica", imagen: "" },
      { id: 71, nombre: "Gingers", precio: 22000, stock: 6, descripcion: "Planta tropical de flor exótica y perfumada", imagen: "" },
      { id: 72, nombre: "Chamaedorea", precio: 28000, stock: 7, descripcion: "Palmera enana ideal para ambientes con poca luz", imagen: "" },
      { id: 73, nombre: "Cycas", precio: 45000, stock: 3, descripcion: "Planta prehistórica de gran presencia decorativa", imagen: "" },
      { id: 74, nombre: "Maranta", precio: 15000, stock: 10, descripcion: "Planta que mueve sus hojas con la luz", imagen: "" },
    ]
  },
  {
    id: 7,
    nombre: "El Rosal",
    descripcion: "Rosas, flores y plantas ornamentales",
    imagen: "",
    ubicacion: "Tucumán",
    productos: [
      { id: 75, nombre: "Rosa Roja", precio: 15000, stock: 10, descripcion: "Rosa clásica de jardín, muy perfumada", imagen: "" },
      { id: 76, nombre: "Hortensia", precio: 22000, stock: 7, descripcion: "Flor grande ideal para exteriores con sombra", imagen: "" },
      { id: 77, nombre: "Rosa Blanca", precio: 15000, stock: 8, descripcion: "Elegante y perfumada, símbolo de pureza", imagen: "" },
      { id: 78, nombre: "Rosa Amarilla", precio: 15000, stock: 9, descripcion: "Alegre y vibrante, ideal para jardines", imagen: "" },
      { id: 79, nombre: "Camellia", precio: 28000, stock: 4, descripcion: "Flor invernal de gran belleza", imagen: "" },
      { id: 80, nombre: "Gardenia", precio: 20000, stock: 6, descripcion: "Flor blanca de perfume intenso", imagen: "" },
      { id: 81, nombre: "Glicina", precio: 18000, stock: 5, descripcion: "Trepadora de flores lilas muy perfumadas", imagen: "" },
      { id: 82, nombre: "Dalia", precio: 12000, stock: 12, descripcion: "Flor de verano en múltiples colores", imagen: "" },
      { id: 83, nombre: "Ranúnculo", precio: 8000, stock: 15, descripcion: "Flor de primavera de pétalos delicados", imagen: "" },
      { id: 84, nombre: "Peonia", precio: 25000, stock: 4, descripcion: "Flor grande y vistosa de corta temporada", imagen: "" },
      { id: 85, nombre: "Crisantemo", precio: 10000, stock: 14, descripcion: "Flor de otoño en múltiples variedades", imagen: "" },
      { id: 86, nombre: "Tulipán", precio: 9000, stock: 16, descripcion: "Bulbo de primavera elegante y colorido", imagen: "" },
      { id: 87, nombre: "Iris", precio: 11000, stock: 10, descripcion: "Flor elegante de temporada primaveral", imagen: "" },
    ]
  },
  {
    id: 8,
    nombre: "Bonsai Studio",
    descripcion: "Bonsais, macetas artesanales y accesorios zen",
    imagen: "",
    ubicacion: "Rosario",
    productos: [
      { id: 88, nombre: "Bonsai Ficus", precio: 75000, stock: 3, descripcion: "Bonsai de ficus con 5 años de cultivo", imagen: "" },
      { id: 89, nombre: "Maceta Artesanal", precio: 18000, stock: 12, descripcion: "Maceta de cerámica hecha a mano", imagen: "" },
      { id: 90, nombre: "Kit Bonsai Inicial", precio: 35000, stock: 6, descripcion: "Todo para empezar en el arte del bonsai", imagen: "" },
      { id: 91, nombre: "Bonsai Olmo", precio: 65000, stock: 2, descripcion: "Clásico del bonsai con hojas pequeñas", imagen: "" },
      { id: 92, nombre: "Bonsai Pino", precio: 90000, stock: 2, descripcion: "Especie noble de cultivo lento y bello", imagen: "" },
      { id: 93, nombre: "Tijera de Poda Bonsai", precio: 12000, stock: 15, descripcion: "Herramienta japonesa de precisión", imagen: "" },
      { id: 94, nombre: "Sustrato Akadama", precio: 8000, stock: 20, descripcion: "Sustrato japonés ideal para bonsai", imagen: "" },
      { id: 95, nombre: "Mesa de Exhibición", precio: 25000, stock: 5, descripcion: "Mesa de madera para exhibir tu bonsai", imagen: "" },
      { id: 96, nombre: "Bonsai Serissa", precio: 45000, stock: 3, descripcion: "Bonsai de flor blanca delicada", imagen: "" },
      { id: 97, nombre: "Alambres de Bonsai", precio: 5000, stock: 30, descripcion: "Set de alambres para modelar ramas", imagen: "" },
    ]
  },
  {
    id: 9,
    nombre: "Acuática Verde",
    descripcion: "Plantas acuáticas, terrarios y jardines de agua",
    imagen: "",
    ubicacion: "Corrientes",
    productos: [
      { id: 98, nombre: "Loto Sagrado", precio: 32000, stock: 4, descripcion: "Flor acuática sagrada de origen asiático", imagen: "" },
      { id: 99, nombre: "Papiro", precio: 14000, stock: 8, descripcion: "Planta acuática de tallo alto y elegante", imagen: "" },
      { id: 100, nombre: "Kit Terrario", precio: 25000, stock: 10, descripcion: "Todo para armar tu propio ecosistema en vidrio", imagen: "" },
      { id: 101, nombre: "Nenúfar Blanco", precio: 28000, stock: 5, descripcion: "Flor acuática clásica para estanques", imagen: "" },
      { id: 102, nombre: "Junco", precio: 10000, stock: 12, descripcion: "Planta acuática de orilla para estanques", imagen: "" },
      { id: 103, nombre: "Lenteja de Agua", precio: 5000, stock: 20, descripcion: "Cobertura natural para estanques", imagen: "" },
      { id: 104, nombre: "Terrario Vidrio 30cm", precio: 35000, stock: 6, descripcion: "Recipiente de vidrio para terrario cerrado", imagen: "" },
      { id: 105, nombre: "Musgo para Terrario", precio: 8000, stock: 15, descripcion: "Musgo natural para decorar terrarios", imagen: "" },
      { id: 106, nombre: "Bomba para Estanque", precio: 18000, stock: 8, descripcion: "Circulación de agua para fuentes y estanques", imagen: "" },
      { id: 107, nombre: "Sustrato Acuático", precio: 12000, stock: 10, descripcion: "Sustrato especial para plantas acuáticas", imagen: "" },
      { id: 108, nombre: "Equiseto", precio: 14000, stock: 7, descripcion: "Cola de caballo acuática decorativa", imagen: "" },
    ]
  },
  {
    id: 10,
    nombre: "Semillas del Campo",
    descripcion: "Semillas, plantines y productos para huerta orgánica",
    imagen: "",
    ubicacion: "Santa Fe",
    productos: [
      { id: 109, nombre: "Mix Semillas Orgánicas", precio: 5000, stock: 50, descripcion: "Variedad de semillas certificadas orgánicas", imagen: "" },
      { id: 110, nombre: "Plantín de Lechuga", precio: 2000, stock: 40, descripcion: "Lechuga lista para trasplantar", imagen: "" },
      { id: 111, nombre: "Tierra Orgánica Premium", precio: 8000, stock: 20, descripcion: "Sustrato enriquecido para huerta y jardín", imagen: "" },
      { id: 112, nombre: "Semillas de Tomate", precio: 3000, stock: 35, descripcion: "Variedad heirloom de gran sabor", imagen: "" },
      { id: 113, nombre: "Semillas de Zapallo", precio: 2500, stock: 30, descripcion: "Variedad criolla de alto rendimiento", imagen: "" },
      { id: 114, nombre: "Semillas de Girasol", precio: 2000, stock: 40, descripcion: "Ideal para jardín y consumo de semillas", imagen: "" },
      { id: 115, nombre: "Vermiculita", precio: 6000, stock: 18, descripcion: "Mejora la retención de agua del sustrato", imagen: "" },
      { id: 116, nombre: "Perlita", precio: 5000, stock: 20, descripcion: "Mejora el drenaje del sustrato", imagen: "" },
      { id: 117, nombre: "Humus de Lombriz", precio: 7000, stock: 15, descripcion: "Abono orgánico de máxima calidad", imagen: "" },
      { id: 118, nombre: "Semillas de Acelga", precio: 2500, stock: 35, descripcion: "Verdura de hoja de rápido crecimiento", imagen: "" },
      { id: 119, nombre: "Semillas de Rúcula", precio: 2500, stock: 30, descripcion: "Hoja aromática para ensaladas", imagen: "" },
      { id: 120, nombre: "Bandeja de Germinación", precio: 4000, stock: 25, descripcion: "Ideal para germinar semillas en casa", imagen: "" },
    ]
  },
  {
    id: 11,
    nombre: "Orquídeas del Plata",
    descripcion: "Orquídeas importadas y plantas de flor exótica",
    imagen: "",
    ubicacion: "Buenos Aires",
    productos: [
      { id: 121, nombre: "Orquídea Phalaenopsis", precio: 35000, stock: 8, descripcion: "La orquídea más popular, fácil de cultivar", imagen: "" },
      { id: 122, nombre: "Orquídea Cattleya", precio: 55000, stock: 3, descripcion: "Gran flor perfumada, reina de las orquídeas", imagen: "" },
      { id: 123, nombre: "Orquídea Dendrobium", precio: 28000, stock: 6, descripcion: "Orquídea con racimos de flores coloridas", imagen: "" },
      { id: 124, nombre: "Orquídea Oncidium", precio: 32000, stock: 5, descripcion: "Lluvia de oro, orquídea de flores pequeñas", imagen: "" },
      { id: 125, nombre: "Orquídea Vanda", precio: 65000, stock: 2, descripcion: "Orquídea epífita de colores vibrantes", imagen: "" },
      { id: 126, nombre: "Orquídea Miltonia", precio: 38000, stock: 4, descripcion: "Orquídea pansy de flores grandes", imagen: "" },
      { id: 127, nombre: "Maceta de Orquídea", precio: 8000, stock: 20, descripcion: "Maceta transparente con ranuras para orquídeas", imagen: "" },
      { id: 128, nombre: "Fertilizante para Orquídeas", precio: 6000, stock: 25, descripcion: "Nutrición específica para orquídeas en flor", imagen: "" },
      { id: 129, nombre: "Corteza de Pino", precio: 5000, stock: 20, descripcion: "Sustrato ideal para orquídeas epífitas", imagen: "" },
      { id: 130, nombre: "Orquídea Zygopetalum", precio: 42000, stock: 3, descripcion: "Flor perfumada de colores contrastantes", imagen: "" },
      { id: 131, nombre: "Kit Cuidado Orquídeas", precio: 15000, stock: 10, descripcion: "Todo lo necesario para mantener tus orquídeas", imagen: "" },
    ]
  },
  {
    id: 12,
    nombre: "Vivero Patagónico",
    descripcion: "Plantas nativas de la Patagonia y especies resistentes al frío",
    imagen: "",
    ubicacion: "Bariloche",
    productos: [
      { id: 132, nombre: "Notro", precio: 18000, stock: 5, descripcion: "Árbol nativo patagónico de flores rojas", imagen: "" },
      { id: 133, nombre: "Calafate", precio: 12000, stock: 8, descripcion: "Arbusto nativo con frutos comestibles azules", imagen: "" },
      { id: 134, nombre: "Coihue en Maceta", precio: 25000, stock: 4, descripcion: "Árbol emblema de la Patagonia en maceta", imagen: "" },
      { id: 135, nombre: "Maitén", precio: 20000, stock: 5, descripcion: "Árbol nativo de hojas pequeñas y colgantes", imagen: "" },
      { id: 136, nombre: "Mutisia", precio: 15000, stock: 6, descripcion: "Trepadora nativa de flor anaranjada", imagen: "" },
      { id: 137, nombre: "Michay", precio: 10000, stock: 8, descripcion: "Arbusto espinoso con flores amarillas", imagen: "" },
      { id: 138, nombre: "Peumo", precio: 22000, stock: 4, descripcion: "Árbol nativo de follaje aromático", imagen: "" },
      { id: 139, nombre: "Ñire", precio: 18000, stock: 5, descripcion: "Arbusto o árbol nativo de alta montaña", imagen: "" },
      { id: 140, nombre: "Berberis", precio: 12000, stock: 9, descripcion: "Arbusto nativo de frutos rojos comestibles", imagen: "" },
      { id: 141, nombre: "Maqui", precio: 14000, stock: 7, descripcion: "Arbusto de frutos negros con antioxidantes", imagen: "" },
    ]
  },
  {
    id: 13,
    nombre: "Follaje & Diseño",
    descripcion: "Plantas de follaje decorativo para diseño de interiores",
    imagen: "",
    ubicacion: "Córdoba",
    productos: [
      { id: 142, nombre: "Calathea Orbifolia", precio: 30000, stock: 6, descripcion: "Hojas plateadas con rayas verdes únicas", imagen: "" },
      { id: 143, nombre: "Ficus Lyrata", precio: 45000, stock: 4, descripcion: "El árbol de moda en diseño de interiores", imagen: "" },
      { id: 144, nombre: "Pothos Marble Queen", precio: 12000, stock: 15, descripcion: "Pothos de hojas jaspeadas en verde y blanco", imagen: "" },
      { id: 145, nombre: "Dracaena Fragrans", precio: 25000, stock: 6, descripcion: "Planta de hojas largas con franja amarilla", imagen: "" },
      { id: 146, nombre: "Yuca Pie de Elefante", precio: 35000, stock: 4, descripcion: "Tronco grueso y hojas largas muy decorativa", imagen: "" },
      { id: 147, nombre: "Philodendron Scandens", precio: 15000, stock: 12, descripcion: "Trepadora rápida de corazón verde", imagen: "" },
      { id: 148, nombre: "Schefflera", precio: 28000, stock: 5, descripcion: "Árbol de interior de hojas compuestas", imagen: "" },
      { id: 149, nombre: "Chlorophytum", precio: 8000, stock: 20, descripcion: "Planta araña, clásica y resistente", imagen: "" },
      { id: 150, nombre: "Alocasia Amazonica", precio: 30000, stock: 5, descripcion: "Hojas oscuras con venas blancas llamativas", imagen: "" },
      { id: 151, nombre: "Epipremnum Neon", precio: 10000, stock: 18, descripcion: "Pothos de color verde neón vibrante", imagen: "" },
      { id: 152, nombre: "Peperomia Obtusifolia", precio: 10000, stock: 15, descripcion: "Suculenta de follaje brillante compacta", imagen: "" },
      { id: 153, nombre: "Maceta Nórdica Blanca", precio: 12000, stock: 20, descripcion: "Maceta minimalista ideal para plantas de diseño", imagen: "" },
    ]
  },
  {
    id: 14,
    nombre: "Aromáticas y Medicinales",
    descripcion: "Hierbas aromáticas, medicinales y plantas para infusiones",
    imagen: "",
    ubicacion: "Mendoza",
    productos: [
      { id: 154, nombre: "Menta Peperita", precio: 4500, stock: 25, descripcion: "Hierba refrescante ideal para infusiones", imagen: "" },
      { id: 155, nombre: "Manzanilla", precio: 4000, stock: 20, descripcion: "Planta medicinal relajante y digestiva", imagen: "" },
      { id: 156, nombre: "Stevia", precio: 6000, stock: 15, descripcion: "Endulzante natural sin calorías", imagen: "" },
      { id: 157, nombre: "Melisa", precio: 4500, stock: 18, descripcion: "Hierba calmante ideal para infusiones", imagen: "" },
      { id: 158, nombre: "Valerian", precio: 5000, stock: 12, descripcion: "Planta medicinal para el estrés y el sueño", imagen: "" },
      { id: 159, nombre: "Cedrón", precio: 4000, stock: 20, descripcion: "Aromática sudamericana clásica para infusiones", imagen: "" },
      { id: 160, nombre: "Hierba Buena", precio: 3500, stock: 25, descripcion: "Menta suave ideal para coctelería y té", imagen: "" },
      { id: 161, nombre: "Orégano", precio: 3500, stock: 28, descripcion: "Hierba culinaria mediterránea esencial", imagen: "" },
      { id: 162, nombre: "Salvia Officinalis", precio: 4500, stock: 15, descripcion: "Aromática con propiedades antiinflamatorias", imagen: "" },
      { id: 163, nombre: "Lavanda Angustifolia", precio: 8000, stock: 15, descripcion: "La variedad más aromática de lavanda", imagen: "" },
      { id: 164, nombre: "Eneldo", precio: 3000, stock: 20, descripcion: "Hierba aromática de sabor anisado", imagen: "" },
      { id: 165, nombre: "Estragón", precio: 4000, stock: 14, descripcion: "Hierba culinaria francesa de aroma único", imagen: "" },
      { id: 166, nombre: "Hipérico", precio: 5000, stock: 10, descripcion: "Hierba antidepresiva de flor amarilla", imagen: "" },
    ]
  },
  {
    id: 15,
    nombre: "Suculentas Express",
    descripcion: "Suculentas y cactus en macetas de diseño para regalo",
    imagen: "",
    ubicacion: "Rosario",
    productos: [
      { id: 167, nombre: "Pack Suculentas x3", precio: 9000, stock: 30, descripcion: "Tres suculentas distintas en macetas de barro", imagen: "" },
      { id: 168, nombre: "Haworthia Fasciata", precio: 6000, stock: 20, descripcion: "Suculenta de interior ideal para poca luz", imagen: "" },
      { id: 169, nombre: "Agave Azul", precio: 15000, stock: 8, descripcion: "Suculenta grande ideal para exteriores", imagen: "" },
      { id: 170, nombre: "Echeveria Lola", precio: 8000, stock: 15, descripcion: "Suculenta roseta de tonos rosados únicos", imagen: "" },
      { id: 171, nombre: "Sedum Rubrotinctum", precio: 7000, stock: 18, descripcion: "Suculenta de hojas que se ponen rojas al sol", imagen: "" },
      { id: 172, nombre: "Crassula Perforata", precio: 6500, stock: 20, descripcion: "Suculenta trepadora de hojas apiladas", imagen: "" },
      { id: 173, nombre: "Aloe Aristata", precio: 8000, stock: 12, descripcion: "Aloe enano compacto ideal para maceta", imagen: "" },
      { id: 174, nombre: "Graptopetalum", precio: 7000, stock: 15, descripcion: "Suculenta gris-rosada muy fácil de propagar", imagen: "" },
      { id: 175, nombre: "Pack Regalo Suculentas", precio: 18000, stock: 10, descripcion: "Caja con 5 suculentas surtidas en caja kraft", imagen: "" },
      { id: 176, nombre: "Maceta Cemento Suculenta", precio: 5000, stock: 25, descripcion: "Maceta de cemento artesanal para suculentas", imagen: "" },
    ]
  },
  {
    id: 16,
    nombre: "Jardín Mediterráneo",
    descripcion: "Olivos, lavandas y plantas de clima mediterráneo",
    imagen: "",
    ubicacion: "San Juan",
    productos: [
      { id: 177, nombre: "Olivo en Maceta", precio: 65000, stock: 3, descripcion: "Árbol centenario en maceta de cerámica", imagen: "" },
      { id: 178, nombre: "Lavanda Angustifolia", precio: 8000, stock: 15, descripcion: "La variedad más aromática de lavanda", imagen: "" },
      { id: 179, nombre: "Tomillo Limón", precio: 5000, stock: 18, descripcion: "Aromática culinaria con aroma cítrico", imagen: "" },
      { id: 180, nombre: "Romero Rastrero", precio: 6000, stock: 15, descripcion: "Variedad de romero tapizante ideal para bordes", imagen: "" },
      { id: 181, nombre: "Lavanda Francesa", precio: 9000, stock: 12, descripcion: "Lavanda de flor vistosa con orejas", imagen: "" },
      { id: 182, nombre: "Cipres Mediterráneo", precio: 30000, stock: 4, descripcion: "Árbol columnar icónico del paisaje mediterráneo", imagen: "" },
      { id: 183, nombre: "Higuera", precio: 35000, stock: 3, descripcion: "Árbol frutal mediterráneo de higos dulces", imagen: "" },
      { id: 184, nombre: "Santolina", precio: 6000, stock: 14, descripcion: "Arbusto plateado aromático resistente a sequía", imagen: "" },
      { id: 185, nombre: "Espliego", precio: 7000, stock: 12, descripcion: "Variedad de lavanda silvestre muy aromática", imagen: "" },
      { id: 186, nombre: "Pistacia Lentisco", precio: 20000, stock: 5, descripcion: "Arbusto mediterráneo resistente y aromático", imagen: "" },
    ]
  },
  {
    id: 17,
    nombre: "Helechos & Sombra",
    descripcion: "Plantas para espacios con poca luz y ambientes húmedos",
    imagen: "",
    ubicacion: "Misiones",
    productos: [
      { id: 187, nombre: "Helecho Cuerno de Alce", precio: 28000, stock: 5, descripcion: "Helecho epífito de forma única para colgar", imagen: "" },
      { id: 188, nombre: "Begonia Rex", precio: 12000, stock: 10, descripcion: "Hojas multicolores ideales para interiores", imagen: "" },
      { id: 189, nombre: "Spathiphyllum", precio: 15000, stock: 12, descripcion: "Purificador de aire con flores blancas", imagen: "" },
      { id: 190, nombre: "Helecho Nido de Pájaro", precio: 18000, stock: 7, descripcion: "Helecho de hojas largas en forma de roseta", imagen: "" },
      { id: 191, nombre: "Aspidistra", precio: 20000, stock: 6, descripcion: "La planta más resistente a la sombra total", imagen: "" },
      { id: 192, nombre: "Oxalis Triangularis", precio: 8000, stock: 15, descripcion: "Trébol morado que se mueve con la luz", imagen: "" },
      { id: 193, nombre: "Adiantum", precio: 14000, stock: 8, descripcion: "Helecho cabello de venus delicado y elegante", imagen: "" },
      { id: 194, nombre: "Chlorophytum", precio: 8000, stock: 18, descripcion: "Planta araña resistente y purificadora", imagen: "" },
      { id: 195, nombre: "Begonia Corallina", precio: 15000, stock: 7, descripcion: "Begonia de flores coral de largo período", imagen: "" },
      { id: 196, nombre: "Cyrtomium", precio: 12000, stock: 9, descripcion: "Helecho de hojas brillantes muy resistente", imagen: "" },
      { id: 197, nombre: "Phlebodium Aureum", precio: 16000, stock: 6, descripcion: "Helecho azulado de aspecto tropical", imagen: "" },
    ]
  },
  {
    id: 18,
    nombre: "Cactus del Desierto",
    descripcion: "Cactus gigantes, columnares y de colección",
    imagen: "",
    ubicacion: "San Luis",
    productos: [
      { id: 198, nombre: "Saguaro Pequeño", precio: 20000, stock: 6, descripcion: "Cactus icónico del desierto en maceta", imagen: "" },
      { id: 199, nombre: "Cactus Totem", precio: 35000, stock: 3, descripcion: "Columnar alto ideal para espacios modernos", imagen: "" },
      { id: 200, nombre: "Gymnocalycium", precio: 8000, stock: 15, descripcion: "Cactus globoso de flores llamativas", imagen: "" },
      { id: 201, nombre: "Cactus Cereus", precio: 25000, stock: 5, descripcion: "Columnar azulado de rápido crecimiento", imagen: "" },
      { id: 202, nombre: "Ferocactus", precio: 18000, stock: 6, descripcion: "Cactus barril con largas espinas coloridas", imagen: "" },
      { id: 203, nombre: "Trichocereus", precio: 15000, stock: 8, descripcion: "Columnar de flores nocturnas perfumadas", imagen: "" },
      { id: 204, nombre: "Melocactus", precio: 22000, stock: 4, descripcion: "Cactus con cefálio rojo en la cima", imagen: "" },
      { id: 205, nombre: "Notocactus", precio: 10000, stock: 12, descripcion: "Cactus globoso de espinas doradas", imagen: "" },
      { id: 206, nombre: "Turbinicarpus", precio: 15000, stock: 8, descripcion: "Cactus miniatura de colección", imagen: "" },
      { id: 207, nombre: "Ariocarpus", precio: 30000, stock: 3, descripcion: "Cactus de lento crecimiento muy buscado", imagen: "" },
    ]
  },
  {
    id: 19,
    nombre: "Plantas Colgantes",
    descripcion: "Plantas para colgar, enredaderas y especies trepadoras",
    imagen: "",
    ubicacion: "Buenos Aires",
    productos: [
      { id: 208, nombre: "Tradescantia Zebrina", precio: 7000, stock: 20, descripcion: "Colgante de hojas moradas y plateadas", imagen: "" },
      { id: 209, nombre: "Hiedra Común", precio: 6000, stock: 25, descripcion: "Trepadora versátil para interior y exterior", imagen: "" },
      { id: 210, nombre: "Epipremnum Aureum", precio: 9000, stock: 18, descripcion: "Pothos resistente ideal para colgar", imagen: "" },
      { id: 211, nombre: "Rhipsalis", precio: 12000, stock: 12, descripcion: "Cactus colgante sin espinas de aspecto exótico", imagen: "" },
      { id: 212, nombre: "Sedum Burrito", precio: 8000, stock: 15, descripcion: "Suculenta colgante de hojas gorditas", imagen: "" },
      { id: 213, nombre: "Ampelopsis", precio: 10000, stock: 10, descripcion: "Trepadora de follaje colorido en otoño", imagen: "" },
      { id: 214, nombre: "Passiflora", precio: 14000, stock: 8, descripcion: "Trepadora de flor exótica y fruto comestible", imagen: "" },
      { id: 215, nombre: "Macramé Porta Maceta", precio: 8000, stock: 20, descripcion: "Colgador artesanal de macramé natural", imagen: "" },
      { id: 216, nombre: "String of Pearls", precio: 15000, stock: 7, descripcion: "Suculenta colgante de hojas redondas como perlas", imagen: "" },
      { id: 217, nombre: "Hoya Carnosa", precio: 18000, stock: 6, descripcion: "Trepadora de hojas carnosas y flor perfumada", imagen: "" },
      { id: 218, nombre: "Dischidia", precio: 16000, stock: 5, descripcion: "Colgante tropical de hojas redondeadas", imagen: "" },
      { id: 219, nombre: "Senecio Rowleyanus", precio: 14000, stock: 8, descripcion: "Collar de perlas, suculenta colgante única", imagen: "" },
    ]
  },
  {
    id: 20,
    nombre: "El Jardín del Litoral",
    descripcion: "Plantas subtropicales, heliconias y flores del litoral",
    imagen: "",
    ubicacion: "Entre Ríos",
    productos: [
      { id: 220, nombre: "Heliconia", precio: 40000, stock: 4, descripcion: "Flor tropical exótica de gran impacto visual", imagen: "" },
      { id: 221, nombre: "Anthurium", precio: 25000, stock: 7, descripcion: "Planta de flor roja lacada muy llamativa", imagen: "" },
      { id: 222, nombre: "Costus", precio: 18000, stock: 6, descripcion: "Planta tropical de follaje decorativo", imagen: "" },
      { id: 223, nombre: "Canna Lily", precio: 15000, stock: 8, descripcion: "Flor tropical de verano en múltiples colores", imagen: "" },
      { id: 224, nombre: "Strelitzia Nicolai", precio: 55000, stock: 3, descripcion: "Ave del paraíso gigante de flor blanca", imagen: "" },
      { id: 225, nombre: "Hibiscus Rosa", precio: 20000, stock: 6, descripcion: "Flor de Jamaica de gran tamaño y colorido", imagen: "" },
      { id: 226, nombre: "Frangipanier", precio: 35000, stock: 4, descripcion: "Árbol tropical de flor perfumada", imagen: "" },
      { id: 227, nombre: "Ixora", precio: 18000, stock: 7, descripcion: "Arbusto tropical de flores rojas en racimos", imagen: "" },
      { id: 228, nombre: "Adenium", precio: 28000, stock: 5, descripcion: "Rosa del desierto de flor llamativa", imagen: "" },
      { id: 229, nombre: "Plumeria", precio: 30000, stock: 4, descripcion: "Árbol tropical de flor perfumada hawaiana", imagen: "" },
      { id: 230, nombre: "Bougainvillea", precio: 22000, stock: 6, descripcion: "Trepadora de brácteas coloridas muy vibrante", imagen: "" },
      { id: 231, nombre: "Gardenia Augusta", precio: 25000, stock: 5, descripcion: "Arbusto de flor blanca de perfume intenso", imagen: "" },
    ]
  }
]